### ISSUE TITLE
Issues don't load when changing to the same repo

### ISSUE THREAD

**Issue by joyngjr** [CATcher-org/WATcher#189]
**Describe the bug**
When changing to the same repo, issues that were previously loaded disappears.

However, issues are still populated as per normal when changing to a different repo.

**To Reproduce**

1. Load any repo
2. Change repo to the current repo
3. See error

**Expected behavior**
Issues remain as it was when changing to the same repo.

**Screenshots**

https://github.com/CATcher-org/WATcher/assets/97519138/116381b2-db18-4324-96fe-1357f2433ca3

**Comment by Eclipse-Dominator** [comment]
Adding some comment from the duplicate issue i made.


**Additional context**
The likely cause of the issue is the cache function `toFetchIssue`. (Haven't verified yet but it is probably this function)
When the repo is changed, the local data is reset but the cache manager didn't. As a result, when the same repo is loaded in, the cache manager detected that there are no changes to the current repo and thus ends the query causing no issues to be loaded in.

**Possible solutions**

- Reset cache manager upon reset along with the local data
- Detect that the new repo is the same as the current one and thus cancel the reset
   - Do take note that the old repo name will redirect to the new repo name after the repo is renamed so going by this approach would require some API checks and not just checking whether the 2 repo org and name is the same

**Comment by LJXSean** [comment]
@Eclipse-Dominator Hi, is this issue still available to work on?
