### ISSUE TITLE
HttpError when Switch repo to same repository

### ISSUE THREAD

**Issue by gycgabriel** [CATcher-org/WATcher#41]
**Describe the bug**
<img width="296" alt="image" src="https://user-images.githubusercontent.com/77230723/181905149-98479c60-87f9-428b-a33f-b2a6d7bc95a6.png">

**To Reproduce**

1. Click submit on switch repo without changing url
2. Click submit repeatedly before issues are fully loaded

**Expected behavior**
Check if repository is same, if it is do not refetch.

**Comment by cheehongw** [comment]
The snackbar was caused by an uncaught error bubbling all the way up to the app level. 

![image](https://user-images.githubusercontent.com/72195240/216824312-735f78db-ea37-445f-b958-836d8acef634.png)

Investigations of the error message indicate that this was caused by the request made in `GithubService::getIssuesAPICall`.
An error in `Promise apiCall` is likely the source of this error
```ts
 private getIssuesAPICall(filter: RestGithubIssueFilter, pageNumber: number): Observable<GithubResponse<GithubIssue[]>> {
    const apiCall: Promise<GithubResponse<GithubIssue[]>> = octokit.issues.listForRepo({
      ...filter,
      owner: ORG_NAME,
      repo: REPO,
      sort: 'created',
      direction: 'desc',
      per_page: 100,
      page: pageNumber,
      headers: { 'If-None-Match': this.issuesCacheManager.getEtagFor(pageNumber) },
      state: 'all'
    });
    const apiCall$ = from(apiCall);   // <--- this line?
    return apiCall$.pipe(
      catchError((err) => {
        return of(this.issuesCacheManager.get(pageNumber));
      })
    );
  }
  ```

**Comment by cheehongw** [comment]
We are running on rxjs 6.5.3. `catchError` does not appear to catch an error on an observable created from a promise.

Same problem has been observed elsewhere for rxjs 6.5.1:
https://stackoverflow.com/questions/59032093/rxjs-catcherror-operator-does-not-catch-an-error-on-an-observable-created-from-a
