### ISSUE TITLE
Asynchronous loading of page data

### ISSUE THREAD

**Issue by Eclipse-Dominator** [CATcher-org/WATcher#83]
**Is your feature request related to a problem? Please describe.**
Currently, the content of the page is loaded synchronously from the repositories via multiple requests. This does not present much of an issue most of the time but it can take a rather long time if there are many pages of PRs and issues to be loaded in especially when there is a lot of PRs and Issues in a repository. 

**Describe the solution you'd like**
Propose the use of asynchronous loading of data to immediately load in the page data once the response is received. We can use a variable to keep track of doneness of loading of data. as well as to show the loading symbol to indicate data is still being loaded in. This enables the page to immediately load in the data once received and it should make the page feel smoother and more responsive.

**Comment by seetohjinwei** [comment]
Hi, I've tried looking into this issue, but noticed that in `github.service.ts`, there are two types of API calls

1. the REST API calls, which are already asynchronous
2. the GraphQL calls, which uses a cursor-based pagination, but I don't think this can be made asynchronous because it requires the previous request's `nextCursor` to perform the subsequent request

Would appreciate some help on where to look instead!

**Comment by Eclipse-Dominator** [comment]
Hello, there are no true async functions in javascript since javascript runs on an event loop, what we can do here is convert the pagination into a generator function. 

You can look into generator functions in javascript. In theory, each time a new page is fetched from graphql, we call `yield` and update some kind of Observables. This allows the progress of the function to be broken up into multiple segments achieving what appears to be immediately loading of data once it's fetched from the repository.
